org: sebastianjm
app: aws-lambda-api-parqueadero
service: aws-lambda-api-parqueadero
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  apiGateway:
    description: ''
    shouldStartNameWithService: false
    metrics: true

functions:
  createUser:
    handler: src/createUser.main
    role: RolAdmin
    events:
      - http:
          path: /createUser
          method: post
  getUsers:
    handler: src/getUsers.main
    role: RolAdmin
    events:
      - httpApi:
          path: /getUsers
          method: get
  getUser:
    handler: src/getUser.main
    role: RolAdmin
    events:
      - httpApi:
          path: /getUser/{id}
          method: get
  updateUser:
    handler: src/updateUser.main
    role: RolAdmin
    events:
      - httpApi:
          path: /updateUser/{id}
          method: put
  deleteUser:
    handler: src/deleteUser.main
    role: RolAdmin
    events:
      - httpApi:
          path: /deleteUser/{id}
          method: delete
  getImageUser:
    handler: src/getImageUser.main
    role: RolAdmin
    events:
      - httpApi:
          path: /getImageUser
          method: get

resources:
  Resources:
    RolAdmin:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: GeneralPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:Query
                    - dynamodb:PutItem
                    - dynamodb:UpdateItem
                    - dynamodb:DeleteItem
                    - dynamodb:GetItem
                    - dynamodb:Scan
                    - dynamodb:DescribeTable
                  Resource: arn:aws:dynamodb:us-east-2:528608382046:table/users_parking
                - Effect: Allow
                  Action:
                    - s3:PutObject
                    - s3:PutObjectAcl
                    - s3:DeleteObject
                    - s3:GetObject
                    - s3:GetObjectVersion
                    - s3:ListBucket
                    - s3:ListAllMyBuckets
                  Resource: arn:aws:s3:::bucket-prueba-parking
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users_parking
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions: 
          - AttributeName: id
            AttributeType: S
        KeySchema: 
          - AttributeName: id
            KeyType: HASH
    
